version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: smartclaim-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongo-data:/data/db
    networks:
      - smartclaim-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: smartclaim-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/smartclaim?authSource=admin
      - FRONTEND_URL=http://localhost:3000
      - BACKEND_URL=http://localhost:3001
      - BASE_URL=http://localhost:3001
      - JWT_SECRET=${JWT_SECRET:-your-secret-key}
      - JWT_EXPIRES_IN=7d
      - SESSION_SECRET=${SESSION_SECRET:-session-secret}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - FACEBOOK_CLIENT_ID=${FACEBOOK_CLIENT_ID}
      - FACEBOOK_CLIENT_SECRET=${FACEBOOK_CLIENT_SECRET}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}
      - PAYPAL_CLIENT_SECRET=${PAYPAL_CLIENT_SECRET}
      - PAYPAL_MODE=sandbox
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - smartclaim-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: smartclaim-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3001
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - smartclaim-network
    stdin_open: true
    tty: true

volumes:
  mongo-data:

networks:
  smartclaim-network:
